
data:
  symbol: "SYNTH"
  freq: "5min"
  years: 3
  seed: 42

features:
  lags: [1, 2, 3, 5, 10]
  roll_windows: [5, 10, 20]
  realized_vol_window: 20
  imbalance_window: 10

labeling:
  method: "quantile"      
  horizon: 1              
  lower_q: 0.25           
  upper_q: 0.75          
  threshold: 0.0          


model:
  type: "RandomForestClassifier"
  params:
    n_estimators: 200
    max_depth: 8
    random_state: 42
    n_jobs: -1

cv:
  n_splits: 5
  gap: 0               

backtest:
  transaction_cost_bps: 1.0  
  decision_threshold: 0.60    
  max_position: 1           
